config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }
  get 'dashboard/index'
  
  
  resources :users do
    resources :prizes
  end
  
  resources :users do
    resources :excercises
  end
  
  resource :dashboard, only: [:index] do
    collection do
      post :search, to: 'dashboard#search'
      get :search, to: 'dashboard#search'
    end
  end
  
  resources :friendships, only: [:show, :create, :destroy]
  

  root to: 'dashboard#index'

end

app/models/excercise.rb
class Excercise < ActiveRecord::Base
  belongs_to :user
  
  validates :duration_in_min, presence: true
  validates :duration_in_min, numericality: { only_integer: true }
  validates :workout, presence: true
  validates :workout_date, presence: true
  validates :user_id, presence: true
  
  default_scope {
    where('workout_date > ?', 7.days.ago).order(workout_date: :desc)
  }
end

app/models/friendship.rb
class Friendship < ActiveRecord::Base
  belongs_to :user
  belongs_to :friend, class_name: "User"
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  has_many :excercises
  
  validates :first_name, presence: true
  validates :last_name, presence: true
  
  has_many :friendships
  has_many :friends, through: :friendships, class_name: "User"
  
  self.per_page = 3
  
  def full_name
    "#{first_name} #{last_name}"
  end
  
  def self.search_by_name(name)
    names_array = name.split(' ')
    if names_array.size == 1
      where('first_name LIKE ? or last_name LIKE ?', "%#{names_array[0]}%", "%#{names_array[0]}%").order(:first_name)
    else
      where('first_name LIKE ? or first_name LIKE ? or last_name LIKE ? or last_name LIKE ?',
      "%#{names_array[0]}%", "%#{names_array[1]}%", "%#{names_array[0]}%", "%#{names_array[1]}%").order(:first_name)
    end
  end
  
  def follows_or_same?(new_friend)
    friendships.map(&:friend).include?(new_friend) || self == new_friend
  end
  
  def current_friendship(friend)
    friendships.where(friend: friend).first
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
    @athletes = User.paginate(:page => params[:page])
  end
  
  def search
    if params[:page]
      @athletes = User.search_by_name(session[:search_name]).paginate(:page => params[:page])
    else
      session[:search_name] = nil
      @athletes = User.search_by_name(params[:search_name]).paginate(:page => params[:page])
    end
    
    session[:search_name] = params[:search_name] if params[:search_name]
  end
  
end

app/controllers/excercises_controller.rb
class ExcercisesController < ApplicationController
    before_action :authenticate_user!
    before_action :set_excercise, except: [:index, :new, :create]
    
    def index
        @excercises = current_user.excercises.all
        @friends = current_user.friends
    end
    
    def new 
       @excercise = current_user.excercises.new 
    end
        
    def create
       @excercise = current_user.excercises.new(excercise_params)
       
       if @excercise.save
           flash[:success] = "Excercise has been created"
           redirect_to [current_user, @excercise]
       else
           flash[:danger] = "Excercise has not been created"
           render :new
       end
    end
    
    def edit
    end
    
    def update
       if @excercise.update(excercise_params) 
          flash[:success] = 'Excercise has been updated'
          redirect_to [current_user, @excercise]
       else
          flash[:danger] = 'Excercise has not been updated'
          render :edit
       end
    end
    
    def show
    end
    
    def destroy
       @excercise.destroy
       flash[:success] = "Excercise has been deleted"
       redirect_to user_excercises_path(current_user)
    end
    
    private
        def excercise_params
            params.require(:excercise).permit(:duration_in_min, :workout, :workout_date, :user_id)
        end
        
        def set_excercise
           @excercise = current_user.excercises.find(params[:id]) 
        end
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
    before_action :authenticate_user!
    
    def create
       friend = User.find(params[:friend_id])
       Friendship.create(friendship_params.merge!(friend_id: params[:friend_id], user_id: current_user.id)) unless current_user.follows_or_same?(friend)
       redirect_to root_path
    end
    
    def show
        @friend = Friendship.find(params[:id]).friend
        @excercises = @friend.excercises.all
    end
    
    def destroy
       @friendship = Friendship.find(params[:id]) 
       if @friendship.destroy
           flash[:success] = "#{@friendship.friend.full_name} unfollowed"
       else
           flash[:danger] = "#{@friendship.friend.full_name} could not be unfollowed"
       end
       redirect_to user_excercises_path(current_user)
    end
    
    private
        def friendship_params
           params.permit(:friend_id, :user_id) 
        end
end

app/controllers/prizes_controller.rb
class PrizesController < ApplicationController
    
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
    
    private
    def sign_up_params
        params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)        
    end 
    
    def account_update_params
       params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, :current_password) 
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
    def devise_error_messages
       return '' if resource.errors.empty?
       
       messages = resource.errors.full_messages.map {
           |msg| content_tag(:li, msg)
       }.join
       html =<<-HTML
        <div class='alert alert-error alert-danger'>
            <a href='#' class='close' data-dismiss='alert' &#215; ></a>
        </div>
        <%= content_tag :div, msg if msg.is_a?(String) %>
        HTML
        
        html.html_safe
    end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/exercises_helper.rb
module ExercisesHelper
end

app/views/dashboard/index.html.erb
<div class='jumbotron'>
    <h1>Workout Lounge!</h1>
    <p>Share your workout with your friends and your family</p>
</div>

<div class='container'>
    <div class='row'>
        <div class='col-md-10'>
            <h2>List of members</h2>
            <%= will_paginate @athletes, renderer: BootstrapPagination::Rails, class: "pull-left paginate" %>
        </div>
    </div>
    
    <div class='row'>
        <% @athletes.each do |athlete| %>
            <div class='col-md-10 well member'>
                <%= athlete.full_name %>
                <% if current_user %>
                    <%= link_to "Follow", friendships_path(friend_id: athlete.id), method: :post,  
                    class: 'btn btn-primary pull-right' unless current_user.follows_or_same?(athlete) %>
                <% end %>
            </div>
        <% end %>
    </div>
</div>

app/views/dashboard/search.html.erb
<div class='container'>
    <div class='row search-result'>
        <% @athletes.each do |athlete| %>
            <div class='col-md-10 well member'>
                <%= athlete.full_name %>
                <% if current_user %>
                    <%= link_to "Follow", friendships_path(friend_id: athlete.id), method: :post,  
                    class: 'btn btn-primary pull-right' unless current_user.follows_or_same?(athlete) %>
                <% end %>
            </div>
            
        <% end %>
    </div>
    <%= will_paginate @athletes, renderer: BootstrapPagination::Rails %>
</div>


    
   

app/views/excercises/_form.html.erb
<div class='row'>
    <div class='col-md-12'>
        
        <%= form_for([current_user, current_user.excercises.new], html: {class: "form-horizontal", role: "form"}) do |f| %>
            
            <% if current_user.excercises.new.errors.any? %>

                <div id="error_explanation">
                    <h2><%= pluralize(@exercise.errors.count, "error") %>
                        prohibited this exercise from being saved: </h2>

                    <ul>
                        <% @exercise.errors.full_messages.each do |message| %>
                            <li><%= message %></li>
                        <% end %>
                    </ul>
                </div>

            <% end %>

            <div class="form-group">
                <div class="control-label col-md-2">
                    <%= f.label :duration_in_min, "Duration (min)" %>

                </div>
                <div class="col-md-10">
                    <%= f.number_field :duration_in_min, class: "form-control" %>
                </div>
            </div>
            <div class="form-group">
                <div class="control-label col-md-2">
                    <%= f.label :workout, "Workout Details" %><br>
                </div>
                <div class="col-md-10">
                    <%= f.text_area :workout, class: "form-control", rows: "10" %>
                </div>
            </div>
            <div class="form-group">
                <div class="control-label col-md-2">
                    <%= f.label :workout_date, "Activity date" %>
                </div>
                <div class="col-md-10">
                    <%= f.text_field :workout_date, class: "form-control", id: 'workout-date' %>
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <%= f.submit class: "btn btn-primary btn-lg" %>
                </div>
            </div>

        <% end %>

    </div>
</div>

app/views/excercises/edit.html.erb
<h1 class='text-center'>Edit excercise for <%= current_user.full_name %></h1>

<div class='row'>
    <div class='col-md-12'>
        
        <%= form_for([current_user, current_user.excercises.find(params[:id])], html: {class: "form-horizontal", role: "form"}) do |f| %>
            
            <% if current_user.excercises.find(params[:id]).errors.any? %>

                <div id="error_explanation">
                    <h2><%= pluralize(@exercise.errors.count, "error") %>
                        prohibited this exercise from being saved: </h2>

                    <ul>
                        <% @exercise.errors.full_messages.each do |message| %>
                            <li><%= message %></li>
                        <% end %>
                    </ul>
                </div>

            <% end %>

            <div class="form-group">
                <div class="control-label col-md-2">
                    <%= f.label :duration_in_min, "Duration (min)" %>

                </div>
                <div class="col-md-10">
                    <%= f.number_field :duration_in_min, class: "form-control" %>
                </div>
            </div>
            <div class="form-group">
                <div class="control-label col-md-2">
                    <%= f.label :workout, "Workout Details" %><br>
                </div>
                <div class="col-md-10">
                    <%= f.text_area :workout, class: "form-control", rows: "10" %>
                </div>
            </div>
            <div class="form-group">
                <div class="control-label col-md-2">
                    <%= f.label :workout_date, "Activity date" %>
                </div>
                <div class="col-md-10">
                    <%= f.text_field :workout_date, class: "form-control", id: 'workout-date' %>
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <%= f.submit class: "btn btn-primary btn-lg" %>
                </div>
            </div>

        <% end %>

    </div>
</div>

<%= link_to 'Show', [current_user, @excercise] %>
<%= link_to 'Back', user_excercises_path(current_user) %>

app/views/excercises/index.html.erb
<div class='col-md-8 col-xs-12'>
    <% unless @excercises.empty? %>
    
    <h1>Listing Excercises</h1>
        <table class='table table-striped'>
            <thead>
                <tr>
                    <th>Duration (min)</th>
                    <th>Workout details</th>
                    <th>Activity date</th>
                    <th colspan='3'></th>
                </tr>
            </thead>
            <tbody>
                <% @excercises.each do |excercise| %>
                    <tr>
                        <td><%= excercise.duration_in_min %></td>
                        <td><%= truncate(excercise.workout, length: 100) %></td>
                        <td><%= excercise.workout_date %></td>
                        <td><%= link_to 'Show', [current_user, excercise] %></td>
                        <td><%= link_to 'Edit', [:edit, current_user, excercise] %></td>
                        <td><%= link_to "Delete", [current_user, excercise], method: :delete, data: {confirm: "Sure?"} %></td>
                    </tr>
                <% end %>
                
            </tbody>
        </table>    
    <% else %>
        <div class='alert alert-danger message-font text-center'>
            No workout yet
        </div>
    
    <% end %>
    <%= link_to 'New Workout', new_user_excercise_path(current_user), class: 'btn btn-primary link' %> 
    
    <%= content_tag :div, '', id: 'chart', data: {workouts: @excercises} %>
</div>

<div class='col-md-4 col-xs-12'>
    <h1 class='text-center'>My Friends</h1>
    <% @friends.each do |friend| %>
        <div class='col-md-offset-3 col-md-6 friend-name'>
            <%= link_to friend.full_name, friendship_path(current_user.current_friendship(friend)) %>
        </div>
        <div class='col-md-3'>
            <div class='btn-unfollow'>
                <%= link_to 'Unfollow', friendship_path(current_user.current_friendship(friend)), method: :delete, data: {confirm: 'Are you sure?'},
                    class: 'btn btn-danger link' %>
            </div>
        </div>
    <% end %>
</div>

app/views/excercises/new.html.erb
<h1 class='text-center'>New Exercise for <%= current_user.full_name %></h1>

<%= render 'form' %>

<div class='row'>
    <div class='col-md-12'>
        <div class='col-md-10 col-md-offset-2'>
            <%= link_to 'Back', user_excercises_path(current_user), class: 'btn btn-primary link', id: 'new-exer-btn' %>
        </div>
    </div>
</div>

app/views/excercises/show.html.erb
<div class="col-xs-12 col-md-10 col-md-offset-1">

    <h2 class="show-header">Showing <%= "#{current_user.first_name}'s Workout Details" %></h2>

    <div class="col-xs-12 col-md-10 well member">
        <div class="col-xs-4">
            <strong>Duration (min):</strong>
        </div>
        <div class="col-xs-8 text-right">
            <%= current_user.excercises.find(params[:id]).duration_in_min %>
        </div>
    </div>
    <div class="col-xs-12 col-md-10 well member">
        <div class="col-xs-4">
            <strong>Workout details:</strong>
        </div>
        <div class="col-xs-8 text-right">
            <%= truncate(current_user.excercises.find(params[:id]).workout, length: 50) %>
        </div>
    </div>
    <div class="col-xs-12 col-md-10 well member">
        <div class="col-xs-4">
            <strong>Activity date:</strong>
        </div>
        <div class="col-xs-8 text-right">
            <%= current_user.excercises.find(params[:id]).workout_date %>
        </div>
    </div>
    <div class="col-xs-12 col-md-10 member">
        <%= link_to "Back", user_excercises_path(current_user) %>
    </div>

</div>

app/views/friendships/show.html.erb
<div class='col-md-8'>
    <p id='notice'><%= notice %></p>
    <h1><%= @friend.full_name %>'s Excercises </h1>
    
    <table class='table table-striped'>
        <thead>
            <tr>
                <th>Duration (min)</th>
                <th>Workout Details</th>
                <th>Activity Date</th>
            </tr>
        </thead>
        
        <tbody>
            <% @excercises.each do |excercise| %>
                <tr>
                    <td><%= excercise.duration_in_min %></td>
                    <td><%= truncate(excercise.workout, length: 100) %></td>
                    <td><%= excercise.workout_date %></td>
                </tr>
            <% end %>
        </tbody>
    </table>

    <br />
    <%= content_tag :div, "", id: "chart", data: {workouts: @excercises} %>
    
    <br>
    <%= link_to "Back", user_excercises_path(current_user), class: 'btn btn-primary link' %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WorkoutApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  
<%= render 'shared/header' %>

<%= render 'shared/main' %>

</body>
</html>

app/views/shared/_header.html.erb
<header role="banner">
  <nav class="navbar navbar-default navbar-fixed-top">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        
        <%= link_to "Athletes Den", root_path, class: "navbar-brand" %>
      </div>
      
      <div class='navbar-collapse collapse' id="bs-example-navbar-collapse-1">
        <ul class='nav navbar-nav'>
          <li class='active'><%= link_to "Home", root_path %><span class='sr-only'>(current)</span></li>
        </ul>
        
        <%= form_tag(search_dashboard_path, class: 'navbar-form navbar-left', role: 'search') do %>
          <div class='form-group'>
            <%= text_field_tag :search_name, nil, placeholder: "Search for friends", class: "form-control" %>
          </div>
          <%= submit_tag "Search", class: 'btn btn-primary' %>
        <% end %>
        
        <ul class='nav navbar-nav navbar-right'>
          
          
          <% if user_signed_in? %>
            <li><%= link_to 'My Lounge', user_excercises_path(current_user) %></li>
            <li><%= link_to 'My Prizes', user_prizes_path(current_user) %></li>
            <li><%= link_to 'Sign out', destroy_user_session_path, method: :delete %></li>
            <div class='navbar-right'>
              <p class='navbar-text'>Signing in as <%= "#{current_user.email}" %></p>
            </div>
          <% else %>
              <li><%= link_to 'Sign up', new_user_registration_path %></li>
              <li><%= link_to 'Sign in', new_user_session_path %></li>
          <% end %>
        </ul>
        
      </div>
    </div>
  </nav>
</header>

app/views/shared/_main.html.erb
<div class='container'>
  <% flash.each do |name, msg| %>
    <div class='alert alert-<%= "#{name}" %>'>
        
      <a href='#' class='close' data-dismiss='alert'>&#215;</a>
      
      <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
    </div>
  <% end %>
  <%= yield %>
</div>